- README.md
- patch.sh
Added multi-version support. (You can add another driver version in array)
Added patch for 396.24 driver.
> Refactoring.

- patch.sh
* 410.48 byte sequence is like 396.54
* libdir is distribution-dependent
* run "cp" in "--preserve" mode
> Adopt for 410.48 and CentOS.

- README.md
- patch.sh
* Minor improvements of built-in help
* Usage options separated from step-by-step guide in order to make both clear
* Added some verbosity to step-by-step guide
Minor edits.
> revamp docs and help

- README.md
- win/README.md
Remove any bias towards local download servers
Removed country-specific download links, added and checked international ones
> International links

- win/README.md
Download process raises too many questions. 
Edit.
> Better description of download process for Win users

- patch.sh
Hopefully, this check is more portable.
> Address #30 - Fix version check on old version of Ubuntu (12.04)

- README.md
- patch.sh
add support for version 390.77 #37
> add support for version 390.77

- win/tools/1337-diff/1337-diff.py
1. 3x speed improvement without significant readability loss
2. Fixed lack of limit implementation
Profiling, code cleanup
> 1337 diff improvements

- win/tools/nv-driver-locator/.gitignore
- win/tools/nv-driver-locator/README.md
- win/tools/nv-driver-locator/gfe_get_driver.py
- win/tools/nv-driver-locator/mailer.py
- win/tools/nv-driver-locator/nv-driver-locator.json.sample
- win/tools/nv-driver-locator/nv-driver-locator.py
Automate driver version tracking to release updates timely. This tool probably will allow us to:
* Decrease maintenance efforts
* Remove dependency from (often inaccurate) user requests filed via issues.
* Reduce support time lag
See related README for implementation overview.
Lots of `mitmproxy`-ing and coding
> Add nv-update-locator utility and support utils/libs

- README.md
Reflects info collected by filed issue #51 
Edit.
> add info about Plex HW transcode

- README.md
Closes #43 
Reflected collected info in docs
> add notes about Unraid

- tools/nv-driver-locator/README.md
- tools/nv-driver-locator/get_nvidia_downloads.py
- tools/nv-driver-locator/gfe_get_driver.py
- tools/nv-driver-locator/nv-driver-locator.py
Ensure all network activities are limited with timeout in order to avoid script hang.
Edit, test.
> nv-driver-locator: timeouts

- win/tools/autopatch/.gitignore
- win/tools/autopatch/README.md
- win/tools/autopatch/autopatch.py
Adds automated generator of patch files from Windows driver installer files. Now we automated almost everything except driver download and manual testing.
Probably in future we can invoke this autopatch by event from nv-update-locator and automatically propose new version for testing by users, but for now it's already looks good enough for me.
Coding, basic testing.
> win: automatic patch generator

- win/README.md
Revamp readme file for Windows patch. This change is intended to reduce usability issues like #55 or [this one](https://github.com/keylase/nvidia-patch/issues/9#issuecomment-452282581).
Edit.
> win: revamp readme file

- win/README.md
- win/ffmpeg_null_10streams.cmd
Resolves #53 
x64dbg inspection, scripting, doc edit.
> addresses issue #53

- .gitmodules
- win/README.md
- win/silent_bump.au3
Improves solution for #53 
Closes #70 
* Added reference to new session bump application
* Added code from issue #70 
* Edited statement about Plex according to latest results in #9
> Issue 53 bis

- README.md
Currently this patch was tested in large variety of Linux distros. Making requirements less specific.
Edit
> linux: remove legacy restriction to OS

- README.md
Updated Step-by-Step with latest version of driver.
No need to edit commands for users.
-
> Updated Readme for latest version

- patch.sh
Closes #79 
Introduces flexible search list for driver location directory.
Added search code, all current possible locations and location from https://github.com/kotuk/nvidia-patch/blob/master/patch.sh
> Introduce search list for driver location

- tools/nv-driver-locator/get_nvidia_downloads.py
- tools/nv-driver-locator/nv-driver-locator.json.sample
- win/tools/autopatch/autopatch.py
Adds support for Creator Ready Driver in backoffice machinery
1. Extended enum in get_nvidia_downloads module of nv-driver-locator
2. Updated default config
3. Added new artifact type for autopatch.py
> Creator Ready Driver

- tools/nv-driver-locator/gfe_get_driver.py
- tools/nv-driver-locator/nv-driver-locator.json.sample
Adds support for CreatorReady driver to GFE module of nv-driver-locator.
1. Updated GFE client version
2. Introduced CRD support
3. Updated cfg example
> GFE CRD support

- README.md
Update Linux README to latest version for convenience.
Edit.
> linux: update readme to latest version

- win/README.md
Easier to read and find specific version if Geforce and Quadro are separated.
> Separate products for ease of read

- tools/nv-driver-locator/README.md
- tools/nv-driver-locator/get_nvidia_downloads.py
- tools/nv-driver-locator/nv-driver-locator.json.sample
- tools/nv-driver-locator/nv-driver-locator.py
- win/tools/autopatch/autopatch.py
Adds automation for Windows Server 2016-2019 drivers.
* Extended nvidia driver locator to query drivers for WS2019 (not really helpful, its metadata has no distinction with WS2012
* Extended autopatch to support `ws2016_x64` platform
> Automation: Windows Server 2016, 2019

- README.md
Updated instruction, 430.14 --> 430.26
-
> Updated instructrion

- README.md
> linux: readme: add notes about dkms

- win/tools/autopatch/autopatch.py
Relates to #136
AP changes:
* Add Windows 7 platform
* Create driver dir recursively
* Do not overwrite existing files
> autopatch improvements

- tools/nv-driver-locator/nv-driver-locator.json.sample
Relates to #136 
Track Win7-8 driver releases.
Edit.
> add win7 channels to default ndl config

- win/README.md
Clarification of extended support
Edit
> extend set of supported windows versions

- tools/nv-driver-locator/nv-driver-locator.py
Improve nvidia-driver-locator emails: include unicode JSON info into message body along with attached ascii json file.
Extended EmailNotifier.
> ndl: improve emails

- tools/nv-driver-locator/get_nvidia_downloads.py
- tools/nv-driver-locator/nv-driver-locator.py
Minimize manual job to reduce maintenance efforts.
Extended get_nvidia_downloads module of nvidia-driver-locator to crawl download URL along with other driver metadata.
> ndl: gnd: add download url

- tools/nv-driver-locator/nv-driver-locator.json.sample
Cover both beta and certified GeForce and Quadro drivers for Windows 7, 8, 8.1
Config edit.
> ndl: look for both certified and beta windows 7 drivers

- win/tools/autopatch/README.md
- win/tools/autopatch/autopatch.py
Reduce maintenance efforts.
Make autopatch capable to process multiple package files in one run at once (convenient to patch entire directory).
> ap: allow batch operation against multiple package files

- README.md
- win/README.md
Add some evidence of practical results confirmed by 3rd party specialists.
Added links to Elpamsoft Plex HW transcoding cheatsheet.
> add benchmarks

- win/tools/autopatch/autopatch.py
Allow autopatch to operate against unpacked library files. It may be useful for inspection of already installed files and troubleshooting issues like #157 
Added new command line option and some logic which skips file extraction, loads file directly and resorts to `stdout` output for direct mode.
> ap: direct mode

- win/README.md
Improve docs. Promote reference to 32bit apps workaround.
Edit.
> win: readme: additional reference for 32bit apps steps

- win/README.md
Add video tutorial for Windows.
Edit.
> video tutorial

- win/tools/autopatch/README.md
Add actual documentation for autopatch utility.
Markdown edit.
> win: ap: update docs

- README.md
> linux: clarify readme about driver installation

- tools/readme-autogen/README.md
- tools/readme-autogen/add_driver.py
- tools/readme-autogen/constants.py
- tools/readme-autogen/readme_autogen.py
- tools/readme-autogen/utils.py
Introduces new tool for driver DB maintenance. This tool accepts basic information about new driver and infers and validates all related data like driver download URL, patch download URL etc.
Splitted common parts of readme-autogen and implemented another script for driver DB maintenance.
> Add driver tool

- tools/readme-autogen/README.md
Add some useful examples of add_driver script usage.
Edit.
> add_driver: add example to docs

- README.md
- drivers.json
Sort out "Tesla" drivers links
Edit, readme autogen.
> linux: add missing links to "Tesla" drivers

- tools/readme-autogen/add_driver.py
Accomodate utility defaults to new patching style.
Updated default names of .1337 files for add_driver.py
> add_driver: update defaults

- win/nvfbcwrp/README.md
- win/nvfbcwrp/nvfbcbody.asm
- win/nvfbcwrp/nvfbcwrp.vcxproj
- win/nvfbcwrp/nvfbcwrp_main.cpp
Adds 32bit compat library to wrap 32bit `NvFBC.dll`
Retargeted build, moved some parts varying from target architecture into preprocessor definitions. Updated instructions and release build links.
> Win: FBC: add 32bit compat library

- win/README.md
Potentially saves people a few minutes if this is encountered.
Adding a notice for it.
> win: Add notice about patch failure in README

- tools/nv-driver-locator/README.md
- tools/nv-driver-locator/get_vulkan_downloads.py
- tools/nv-driver-locator/nv-driver-locator.json.sample
- tools/nv-driver-locator/nv-driver-locator.py
Related to #224. Track Vulkan drivers automatically so users wont have to ask for them.
Python Python Python Python Python Python Python Python
> ndl: track Vulkan Beta Drivers

- tools/readme-autogen/templates/windows_readme_master.tmpl
- win/README.md
> add notice about Discord

- README.md
- tools/readme-autogen/templates/linux_readme_master.tmpl
- tools/readme-autogen/templates/windows_readme_master.tmpl
- win/README.md
Mirror git repo in IPFS as well
Introduced separate IPNS key; implemented git repo export: https://docs.ipfs.io/how-to/host-git-style-repo/
> ipfs: add git mirror

- tools/readme-autogen/templates/windows_readme_master.tmpl
- win/README.md
Update video guide to new one which covers latest workflow.
Template edit; autogen.
> doc: update video guide

- win/skip_sig_check/index.html
Add usable page for skip_sig_check in IPFS mirror.
Generated index.html from markdown and embedded reg-file into page body as a Data URL.
> skip_sig_check: add page for IPFS mirror

- tools/readme-autogen/README.md
- win/tools/autopatch/README.md
> doc update

- win/Win_1337_Apply_Patch.git.cid
Mirror Win_1337_Apply_Patch git snapshot to IPFS
`ipfs add`  and `ipfs pin add` on few nodes; commited CID file
> maintenance: mirror Win_1337_Apply_Patch sources repo

- drivers.json
> fix url for driver version 450.51.06

- README.md
- tools/readme-autogen/templates/linux_readme_master.tmpl
- tools/readme-autogen/templates/windows_readme_master.tmpl
- win/README.md
Update readme's and their templates with new structure and additional info
Edit.
> Readme update

- README.md
- drivers.json
- patch-fbc.sh
- patch.sh
Add linux driver version 455.23.05
Hash match
> linux: driver version 455.23.05

- README.md
- drivers.json
- patch-fbc.sh
- patch.sh
Add driver version 455.28 for Linux
Educated guess w/o test
> linux: add driver version 455.28

- README.md
- drivers.json
- patch-fbc.sh
- patch.sh
linux: add driver version 455.32.00
Hash match
> linux: add driver version 455.32.00

- tools/nv-driver-locator/README.md
- tools/nv-driver-locator/get_deb_drivers.py
- tools/nv-driver-locator/nv-driver-locator.json.sample
- tools/nv-driver-locator/nv-driver-locator.py
Resolves #333 
Implemented new Channel for nvidia-driver-locator which is capable to poll Nvidia CUDA driver repos and Ubuntu repos.
> Linux nvidia deb channel

- win/nvfbcwrp/README.md
https://github.com/keylase/nvidia-patch/issues/359
> win: nvfbcwrp: mention registry entry

- README.md
- drivers.json
- patch.sh
Fix #357 
GDB session on HW provided by courtesy of @Vercas
> linux: add driver version 460.32.03

- tools/patch-tester/patch-tester.sh
- win/tools/patch-tester/patch-tester.bat
- win/tools/patch-tester/patch-tester.ps1
Adds tester scripts to verify patching was completed successfully.  Can help out with situations like #630 
Super simple and basic bash/batch/powershell scripts derived from the Wiki page for ease of patch verification.
> Add tester scripts

- drivers.json
It was missing from the original PR merge
`add_driver.py -L 535.86.10`
> Add missing driver 535.86.10 to drivers.json

- .github/workflows/gen_win_patches.yml
Studio driver workflow was broken, fix it just in case we ever need it in future.
Tested on my fork https://github.com/jailuthra/nvidia-patch/actions/runs/6494924187/job/17638827156
> actions: Fix workflow for studio release

- .github/workflows/gen_linux_patches.yml
- tools/autopatch/find_bytecode.sh
FIxes #683 
Tested various scenarios on my fork
> GH Actions: Add workflow for linux autopatch

- tools/patch-tester/patch-tester.sh
Update the patch_tester.sh script so that it aligns with the wiki and is capable of testing more than 8 sessions.
> linux: update patch tester script.

- patch-fbc.sh
- patch.sh
Just to add a simple root check. I know that people will see the "permission denied" thing but honestly just adding this makes life easier.
I added 8 lines of code. It ain't that hard to see.
> Added root check to patch.sh and patch-fbc.sh
