keylase/nvidia-patch

patch.sh

Adding suport for 396.54
Using gtx 970 and Ubuntu 18.04 with kernel  4.18.7
Tested with plex tranconder

Added driver suport for 396.54

---

README.md

Fixes issue #18
New URLs has been checked using `curl` and replaced in README. Some of links (versions 396.26 and 396.37) returning HTTP 404, but same behavior takes place with old URLs too.

README: country agnostic URLs

---

patch.sh

* Fixes bug: message 'Something went wrong. Check nvidia driver' never displayed because `$?` always zero due to pipe containing last `head` which always succeeds.
* Fix: https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing
* Fix: https://www.shellcheck.net/wiki/SC2181 -- Check exit code directly with
* Introduces strict mode of BASH operation:
* Fail and exit on any undefined variables
* Fail and exit on command errors
* Fail pipes if any command in pipe fails (it was essential for `nvidia-smi` pipe)
General purpose of changes made is to make code safer to run and eliminate possibility of unexpected behavior.
Linted code with latest stable `shellcheck`, located potential and actual issues.

Results of shellcheck hunt

---

win/tools/1337-diff/1337-diff.py
win/tools/1337-diff/README.md

Minimize efforts spent for new windows patches and speedup its production
Implemented tool, which casts difference between original and patched file into applicable `.1337` binary patch

Add tool for producing .1337 patches

---

README.md
win/README.md

* Minor appearance fixes
* Bold emphasis on Windows and Linux distinction in main README.md to help some people not getting themselves lost
* Also reflects #51 on Windows README page
Edit.

doc update

---

patch.sh

Our script for linux already works safely and halts on all errors. But sometimes user may spoil file with CRLF newlines (#75) and `pipefail` option is not applied then. This change ensures all interpreter options applied and script is failing safely in this case.
Edit.

Guard from CRLF newlines

---

patch.sh

I tried using `bash ./patch.sh` to patch my Nvidia driver. I kept getting the `ERROR: cannot detect driver directory` error even though I had made sure I installed the Nvidia drivers correctly. After checking the [file list](https://packages.debian.org/stretch/amd64/libnvidia-encode1/filelist) for the `libnvidia-encode1` package, I saw that the driver locations that get checked by `patch.sh` were missing the directory for the `nvidia-current` driver on Debian 9.
Adding the missing directory to the list of directories fixes this issue and the patch succeeds.

Add driver location directory for Debian 9 using nvidia-current driver

---

tools/nv-driver-locator/README.md
tools/nv-driver-locator/get_nvidia_downloads.py
tools/nv-driver-locator/nv-driver-locator.json.sample

Related to #108 
Introduces support for Windows Server 2012R2 in nvidia-driver-locator
New enum valued, updated doc and sample config.

nv-driver-locator: add support for Windows Server drivers

---

win/tools/autopatch/autopatch.py

Adds automation for Windows Server drivers
Introduced some weak detection of Windows Server driver based on installer file name since setup.cfg are identical for server and non-server driver packages.

ap: add some support for Windows Server drivers

---

tools/nv-driver-locator/README.md
tools/nv-driver-locator/get_cuda_downloads.py
tools/nv-driver-locator/nv-driver-locator.json.sample
tools/nv-driver-locator/nv-driver-locator.py

Related to #107.
Some versions of Nvidia Driver are distributed only in bundle with CUDA Toolkit. But now it is known such versions are often distributed as preinstalled SW. For this reason it is reasonable to track CUDA Toolkit releases in order to get notified about new rare driver versions.
Introduced new driver channel for nv-driver-locator.

ndl: track cuda toolkit releases

---

win/tools/autopatch/autopatch.py

Change directory prefix created by autopatch tool to reflect latest rename of CreatorReady Driver to Studio Driver.
Fix

autopatch: change prefix for studio driver

---

README.md
patch.sh

This PR implements features discussed in #162 and aimed to make automation around patch.sh straightforward. As a result, it will be trivial to put together automated patching for latest driver updates.
* Refactored patch.sh to split code into routines and define mutually exclusive modes of operation.
* New mode of operation: check if specific version is supported. Example: `./patch.sh -c 430.50`
* New mode of operation: list supported versions. Example: `./patch.sh -l`
* Idempotent invocation:  subsequent invocations of `patch.sh` detect driver file different from original and do nothing.

Automation-friendly patch.sh

---

tools/nv-driver-locator/get_nvidia_downloads.py
tools/nv-driver-locator/nv-driver-locator.json.sample

Related to #169 
It seems Tesla driver along with CUDA Toolkit are often shipped by OEMs and package maintainers even for GeForce cards. Therefore these drivers are of interest for us as well.
Edit, test.

ndl: track tesla drivers as well

---

win/nvfbcwrp/README.md
win/nvfbcwrp/framework.h
win/nvfbcwrp/nvfbcdefs.h
win/nvfbcwrp/nvfbcwrp.vcxproj
win/nvfbcwrp/nvfbcwrp.vcxproj.filters
win/nvfbcwrp/nvfbcwrp_main.cpp

Allows nvfbcwrp to capture and replay `privateData` used by entitled apps like GeForce Experience/Shadow Play etc.
* Added Unicode paths support, rewritten definitions in encoding-agnostic fashion.
* Added control via env variable which tells wrapper to save `privateData` passed through it.
* Added control via env variable which tells wrapper to use specific private data vector from file instead of built-in private data vector.
* Updated docs.

win: fbc: sniff/replay

---

patch-fbc.sh
patch.sh

Sometimes patching nvidia drivers fails inside docker container with no reason. This PR will add more descriptive info on what actually happens on failure.
In order to adding more debug info this solution fixed issue #267. I think that problem was in checking return value of `nvidia-smi` command: sometimes it fails despite that variable contains correct driver version.

Add more descriptive info about driver version detection failure #267

---

tools/nv-driver-locator/get_vulkan_downloads.py

Fix #297 
Vulkan Beta downloads page contains odd `</p>` tag shortly after header which we consider as a start of section with driver downloads, so it breaks `next_siblings` iteration in `bs4`. Switched to `find_all_next()` iterator with condition to stop on next `<h4>` tag.

ndl: workaround broken layout on Vulkan Beta downloads page

---

README.md
patch-fbc.sh
patch.sh

Make it possible to specify driver version to patch without running `nvidia-smi`.
We use nvidia-patch during automated installation process and `nvidia-smi` is not available because the actual GPU is not connected to the computer yet. This new option allows us to patch the driver even with GPU not connected.
I added `-d VERSION` switch to both `patch.sh` and `patch-fbc.sh` to make it possible to specify driver version to patch manually. It is used in `patch_common` instead of running `nvidia-smi`.

linux: add -d switch to specify nvidia driver version manually

---

README.md
drivers.json
patch-fbc.sh

Enable NvFBC on driver versions 460.27.04 and 460.32.03
Fixes #365 
Educated guess, referencing x86-Assembly documentation
Tested with OBS NvFBC plugin against both driver versions on a GTX 1070

linux: add NvFBC for driver versions 460.27.04 and 460.32.03

---

README.md
drivers.json
patch-fbc.sh

Add NvFBC patches for 460.39 and Vulkan Beta 455.50.03
sha256sum for 455.50.02 > 455.50.03 and 460.32.03 > 460.39 respectively are identical, so patches will be unchanged.

Add NvFBC patch for 460.39 and 455.50.03

---

tools/readme-autogen/add_driver.py

Add an option to add_driver utility to allow for adding a driver version without the NVENC patch

Add the ability to add NvFBC patches without NVENC

---

README.md
drivers.json
patch-fbc.sh

Adds NvFBC patch for 470.42.01
- Sha256sum did not match, verified area affected by patch was unaffected by these changes.
- Tested patch using OBS FBC plugin on GTX 1070

Add NvFBC patch for 470.42.01

---

README.md
patch-fbc.sh
patch.sh

This PR allows patching the [Flatpak NVIDIA drivers](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia), which is useful for Flatpak apps using NVENC/NvFBC (mainly useful for [OBS Studio](https://flathub.org/apps/details/com.obsproject.Studio) with [this plugin](https://gitlab.com/fzwoch/obs-nvfbc) I'm preparing to package; and also [Kdenlive](https://flathub.org/apps/details/org.kde.kdenlive)).
* I've added the `-f` flag to both scripts , which when used, enables patching Flatpak drivers. Backup and restore should also work flawlessly for the Flatpak version.
* Automatic backup with `-f` adds a `.flatpak` suffix to the filenames, in order to differentiate them from backup files from the host drivers.

Support patching Flatpak NVIDIA drivers

---

patch.sh

In my last commit I made a mistake (https://github.com/keylase/nvidia-patch/issues/460)
Replace line 286 from 
["470.82.00"]='libnvidia-fbc.so'
to
["470.82.00"]='libnvidia-encode.so'

Fix error on patch-sh

---

.gitignore
win/tools/autopatch/.gitignore
win/tools/autopatch/README.md
win/tools/autopatch/autopatch.py

Automatically download the driver file for windows tool auto patcher, saves some time downloading and moving it by hand
Support just the version number or the url to download the file.   
Version number only supports the win10-11 dch driver (as its hardcoded).   
Also add a global basic python `.gitignore`
```
python.exe autopatch.py temp/512.95-desktop-win10-win11-64bit-international-dch-whql.exe
python.exe autopatch.py https://international.download.nvidia.com/Windows/512.95/512.95-desktop-win10-win11-64bit-international-dch-whql.exe
python.exe autopatch.py 512.95
```

add installer downloader by version or url

---

tools/readme-autogen/README.md
tools/readme-autogen/constants.py

just adds the new nv*/micro* driver variant which is used as a few versions already.   
i migrated the older drivers in the next pr.
dch drivers have a diffrent url and the add_driver.py did not support it (404 without dch). I guess u set the url manual in the past.

support dch driver variant

---

win/README.md

This change resolves keylase/nvidia-patch#453 which identified that Windows 11 is supported, and was meant to be updated in the README files, but this was never completed. This is now done.
Simply changed README file to remove confusion on whether or not Windows 11 is supported or not

Changed Windows README to show Windows 11 is now supported

---

patch-fbc.sh
patch.sh

Fix #560 
Untested, checking debian/ubuntu package file lists I do not see any change in the driver install paths. But some users report that their libs end up in `/usr/lib` so adding that in the search path.

patch(-fbc).sh: Add /usr/lib to search path

---

win/tools/autopatch/autopatch.py

This will re-use a downloaded driver in temp to avoid 2nd download for 32bit and 64bit patching.
Only affecting the windows tool script.

[FR] WinTool: Re-use a downloaded driver in temp

---

README.md

Some distributions keep changing the location of the nvenc and nvfbc libraries, and patch script cannot find it. Recommend using the official installer instead.

README: Recommend nvidia official installer

---

patch-fbc.sh
patch.sh

We use `sed` to replace original bytes by patched ones, but unfortunately `sed` doesn't report any errors when this substitution fails.
Now, before actually running `sed`, we check if these bytes that are soon to be replaced, actually exist in the driver file.
This will hopefully help people from submitting [wrong bytes](https://github.com/keylase/nvidia-patch/pull/631)... :smiling_face_with_tear: 
I manually tested this on the newly released 470.199.02 drivers by setting invalid bytes in `patch-fbc.sh` (and `patch.sh`), and thankfully the script caught it:
And afterward I tested with the correct bytes and it also worked.

linux: ensure bytes are valid before patching

---

patch-fbc.sh
patch.sh

Used by:
https://packages.debian.org/bookworm/amd64/libnvidia-encode1/filelist https://packages.debian.org/bookworm/amd64/libnvidia-tesla-encode1/filelist https://packages.debian.org/bookworm/amd64/libnvidia-tesla-470-encode1/filelist
Support patching for Debian-packaged Nvidia driver (Tesla version)
N/A

patch(-fbc).sh: Add Debian's Tesla driver to search path

---

patch-fbc.sh
patch.sh

When running with sudo, the flatpak context of the user changes to root, this doesn't work if the driver was installed under the user's flatpak (The default method for many distros/applications).
This will first attempt to locate the driver path using the previous method (system flatpak). If it fails to find that, it will fall back to logging in as the user that invoked sudo & checking their flatpak context (user flatpak).
Since the copy preserves permissions & ownership, the user will still have access to the /opt/nvidia path where the backup is located, and the replaced driver also has the correct permissions as well. 
This method was tested and confirmed working with the `org.freedesktop.Platform.GL.nvidia-535-98` driver on Pop!_OS 22.04 LTS. But should be compatible with any OS with …

Fixed flatpak driver installed in user context not found

---

.github/workflows/README.md
.github/workflows/gen_win_patches.yml
win/tools/autopatch/.gitignore
win/tools/autopatch/autopatch.py

To create patches to a new driver version simply create a new release with the following name schema:
- For DCH: `win-dch-536.67`
- For Studio: `win-studio-536.67`
- If you need to rerun append `-{try}` e.g. `win-dch-536.67-2`
Tagname same as release name.
If the patch file exist for a version, they will get deleted and recreated.   
The patches will be added as asset to the release - users can follow releases and get notification on new patch/driver version.
> Currently only for windows10 patches
Successfull build on my fork: https://github.com/reloxx13/nvidia-patch/actions/runs/5592762761/jobs/10225640154

Add github action for windows patches

---

.github/workflows/gen_win_patches.yml
tools/readme-autogen/constants.py
win/tools/autopatch/autopatch.py

Tagging release on an older commit (and then adding assets with new patch) is unnecessarily confusing.
Instead use Workflow dispatch for triggering new runs. This also allows us to take more complicated arguments and commit description (for fixes tags) etc.
Also support DCH (Hotfix) in the scripts.
Tested the workflow on my fork

Workflow improvements

---

patch-fbc.sh
patch.sh

Adds a `-j` option to export the patch list as JSON, providing an output like: [patch.json](https://github.com/icewind1991/nvidia-patch-nixos/blob/main/patch.json)
This makes it easier for external tooling to re-use the patch information.
I've been using this logic for a while in my [nvidia-patch for NixOS](https://github.com/icewind1991/nvidia-patch-nixos) project by patching the scripts.
Partial solution for #601

add option to export patches as JSON

---

tools/readme-autogen/templates/windows_readme_master.tmpl
win/README.md

Fixes [#851 ](https://github.com/keylase/nvidia-patch/issues/828#issuecomment-2385872945)
- Updated the link to the `Win_1337_Apply_Patch` tool to point to updated forked repository, which includes improvements and bug fixes.
- Added an alternative option for users to apply patches using a new PowerShell script (`Win_1337_Apply_Patch_Powershell`), also linked in the README.
- Maintained the original instructions while providing users with multiple options for patch application.

win: Update windows readme-autogen template to reference new forked patch tools and new PowerShell script

---

drivers.json

Broken json format, missing closing bracket "}" at line #4811. Also fixes NVCleanstall error.
Fixes the broken format of the json.
Fixes NVCleanstall error.

win: hotfix - Update drivers.json
